# AMD Eco/Travel Mode
# Forces the session to run on the Integrated GPU
# The dGPU will ideally sleep until called with 'prime-run'

env = AQ_DRM_DEVICES,/dev/dri/card1:/dev/dri/card0
env = LIBVA_DRIVER_NAME,radeonsi
env = XDG_SESSION_TYPE,wayland
# env = GBM_BACKEND,nvidia-drm # Do NOT set this for AMD
# env = __GLX_VENDOR_LIBRARY_NAME,mesa # Optional, defaults are usually fine
